import { VibeConfig } from './types';

export const presets: VibeConfig[] = [
  // --- NEW EXOTIC SIMULATIONS (10) ---
  {
    id: "colliding-worlds-shatter",
    name: "Colliding Glass Worlds",
    description: "Two massive glass planets crash in slow motion, shattering into thousands of refractive shards.",
    palette: ["#ccffff", "#00ffff", "#ffffff", "#000033"],
    background: { type: "solid", color1: "#000000" },
    geometry: { type: "collidingWorlds", count: 3000, sizeRange: [0.1, 0.5], material: "physical" },
    motion: { cameraDrift: true, cameraSpeed: 0.1, pattern: "explosion", intensity: 1.0 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 1.2, glow: 0.8, grain: 0.1, chromaticAberration: 0.2 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 5000 }
  },
  {
    id: "siege-fire-arrows",
    name: "Siege of Fire",
    description: "Thousands of flaming arrows rain down on a dark fortress, igniting it upon impact.",
    palette: ["#ff4400", "#ffaa00", "#111111", "#ffcc00"],
    background: { type: "gradient", color1: "#050000", color2: "#1a0500" },
    geometry: { type: "siegeFire", count: 2000, sizeRange: [0.1, 0.3], material: "matte" },
    motion: { cameraDrift: true, cameraSpeed: 0.05, pattern: "linearFast", intensity: 1.0 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 1.5, glow: 0.6, grain: 0.3, chromaticAberration: 0.1 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 3000 }
  },
  {
    id: "supernova-remnant",
    name: "Supernova Remnant",
    description: "A dying star explodes, sending shockwaves of colorful gas and debris into the void.",
    palette: ["#ff0066", "#aa00ff", "#00ccff", "#ffffff"],
    background: { type: "nebula", color1: "#000011", color2: "#000000" },
    geometry: { type: "supernova", count: 4000, sizeRange: [0.1, 0.8], material: "neon" },
    motion: { cameraDrift: true, cameraSpeed: 0.2, pattern: "explosion", intensity: 1.0 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 2.0, glow: 1.0, grain: 0.2, chromaticAberration: 0.4 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 5000 }
  },
  {
    id: "neon-city-drive",
    name: "Neon City Drive",
    description: "An infinite flight through a dense cyberpunk metropolis.",
    palette: ["#00ffcc", "#ff0099", "#110033", "#000000"],
    background: { type: "solid", color1: "#050011" },
    geometry: { type: "neonCity", count: 1000, sizeRange: [1, 5], material: "neon" },
    motion: { cameraDrift: false, cameraSpeed: 0.0, pattern: "linearFast", intensity: 1.5 },
    overlay: { glyphsEnabled: true, glyphStyle: "matrixCode", glyphOpacity: 0.3 },
    postProcessing: { bloom: 1.2, glow: 0.8, grain: 0.1, chromaticAberration: 0.3 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 2000 }
  },
  {
    id: "black-hole-horizon",
    name: "Event Horizon",
    description: "A supermassive black hole with a swirling accretion disk and light distortion.",
    palette: ["#ffaa55", "#aa4400", "#000000", "#ffffff"],
    background: { type: "solid", color1: "#000000" },
    geometry: { type: "blackHole", count: 5000, sizeRange: [0.05, 0.2], material: "neon" },
    motion: { cameraDrift: true, cameraSpeed: 0.1, pattern: "spiral", intensity: 1.0 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 1.0, glow: 0.5, grain: 0.4, chromaticAberration: 0.5 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 5000 }
  },
  {
    id: "tornado-vortex",
    name: "Chaos Vortex",
    description: "A raging tornado of particles destroying everything in its path.",
    palette: ["#888888", "#cccccc", "#444444", "#000000"],
    background: { type: "gradient", color1: "#111111", color2: "#333333" },
    geometry: { type: "tornado", count: 4000, sizeRange: [0.1, 0.4], material: "matte" },
    motion: { cameraDrift: true, cameraSpeed: 0.05, pattern: "spiral", intensity: 2.0 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 0.2, glow: 0.1, grain: 0.5, chromaticAberration: 0.1 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 5000 }
  },
  {
    id: "biolum-abyss",
    name: "Bioluminescent Abyss",
    description: "Deep underwater flora swaying gently, emitting soft light.",
    palette: ["#00ff88", "#0088ff", "#000033", "#440088"],
    background: { type: "gradient", color1: "#000011", color2: "#001133" },
    geometry: { type: "bioluminescentAbyss", count: 800, sizeRange: [0.5, 2], material: "neon" },
    motion: { cameraDrift: true, cameraSpeed: 0.05, pattern: "breathing", intensity: 0.5 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 1.8, glow: 1.0, grain: 0.1, chromaticAberration: 0.1 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 1000 }
  },
  {
    id: "thunderstorm-clouds",
    name: "Electric Thunderstorm",
    description: "Volumetric clouds illuminated by random lightning strikes and heavy rain.",
    palette: ["#222233", "#444455", "#ffffff", "#000000"],
    background: { type: "solid", color1: "#050510" },
    geometry: { type: "thunderstorm", count: 2000, sizeRange: [1, 3], material: "matte" },
    motion: { cameraDrift: false, cameraSpeed: 0.0, pattern: "noiseFlow", intensity: 0.8 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 0.5, glow: 0.2, grain: 0.3, chromaticAberration: 0.0 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 3000 }
  },
  {
    id: "crystal-growth",
    name: "Crystal Cave Growth",
    description: "Sharp crystals rapidly growing and refracting light in a dark cave.",
    palette: ["#ff00ff", "#00ffff", "#ffffff", "#110022"],
    background: { type: "solid", color1: "#000000" },
    geometry: { type: "crystalGrowth", count: 500, sizeRange: [0.5, 2], material: "physical" },
    motion: { cameraDrift: true, cameraSpeed: 0.1, pattern: "breathing", intensity: 0.5 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 0.8, glow: 0.6, grain: 0.1, chromaticAberration: 0.3 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 1000 }
  },
  {
    id: "pixel-sort-void",
    name: "Pixel Sort Void",
    description: "A glitch-art simulation where reality is sorted by color.",
    palette: ["#ff0000", "#00ff00", "#0000ff", "#ffff00"],
    background: { type: "grid", color1: "#000000", color2: "#111111" },
    geometry: { type: "pixelSort", count: 4096, sizeRange: [0.2, 0.2], material: "neon" },
    motion: { cameraDrift: false, cameraSpeed: 0.0, pattern: "linearFast", intensity: 1.0 },
    overlay: { glyphsEnabled: true, glyphStyle: "circuits", glyphOpacity: 0.2 },
    postProcessing: { bloom: 0.5, glow: 0.3, grain: 0.0, chromaticAberration: 0.8 },
    performance: { targetFPS: 60, quality: "medium", maxParticles: 5000 }
  },

  // --- RESTORED & UPGRADED REQUESTS ---
  {
    id: "solar-surface-storm",
    name: "Solar Surface Storm",
    description: "A violent star surface with magnetic loops and coronal mass ejections.",
    palette: ["#ff3300", "#ffaa00", "#550000", "#ffff00"],
    background: { type: "solid", color1: "#1a0500" },
    geometry: { type: "solarSphere", count: 50, sizeRange: [4, 4], material: "neon" },
    motion: { cameraDrift: true, cameraSpeed: 0.1, pattern: "pulsing", intensity: 0.8 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 1.5, glow: 1.0, grain: 0.2, chromaticAberration: 0.1 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 100 }
  },
  {
    id: "liquid-glass-nebula",
    name: "Liquid Glass Nebula",
    description: "Thousands of refractive glass spheres flowing in a zero-G fluid simulation.",
    palette: ["#a8c0ff", "#ffffff", "#3f2b96"],
    background: { type: "nebula", color1: "#000000", color2: "#111122" },
    geometry: { type: "liquidField", count: 3000, sizeRange: [0.3, 0.8], material: "physical" },
    motion: { cameraDrift: true, cameraSpeed: 0.1, pattern: "noiseFlow", intensity: 0.4 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 0.8, glow: 0.5, grain: 0.1, chromaticAberration: 0.2 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 5000 }
  },
  {
    id: "prismatic-hyperspace",
    name: "Prismatic Hyperspace",
    description: "A high-speed infinite tunnel trip at warp speed.",
    palette: ["#ff00ff", "#00ffff", "#ffffff", "#0000ff"],
    background: { type: "solid", color1: "#000000" },
    geometry: { type: "warpTunnel", count: 120, sizeRange: [1, 5], material: "neon" },
    motion: { cameraDrift: false, cameraSpeed: 0.0, pattern: "linearFast", intensity: 2.0 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 1.2, glow: 0.8, grain: 0.05, chromaticAberration: 0.8 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 1000 }
  },
  {
    id: "zen-stones-stack",
    name: "Zen Garden Stones",
    description: "Procedurally stacked balanced stones floating in a void.",
    palette: ["#888888", "#555555", "#cccccc", "#222222"],
    background: { type: "gradient", color1: "#e0e0e0", color2: "#ffffff" },
    geometry: { type: "stoneStack", count: 20, sizeRange: [0.5, 1.5], material: "matte" },
    motion: { cameraDrift: true, cameraSpeed: 0.1, pattern: "breathing", intensity: 0.1 },
    overlay: { glyphsEnabled: true, glyphStyle: "zenRunes", glyphOpacity: 0.15 },
    postProcessing: { bloom: 0.1, glow: 0.0, grain: 0.2, chromaticAberration: 0.0 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 100 }
  },
  {
    id: "borealis-curtain",
    name: "Borealis Curtain",
    description: "Silk-like curtains of green and purple light waving in the sky.",
    palette: ["#00ff99", "#0000ff", "#aa00ff"],
    background: { type: "solid", color1: "#000511" },
    geometry: { type: "ribbonWave", count: 15, sizeRange: [5, 20], material: "hologram" },
    motion: { cameraDrift: true, cameraSpeed: 0.05, pattern: "noiseFlow", intensity: 0.2 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 1.0, glow: 0.8, grain: 0.1, chromaticAberration: 0.0 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 20 }
  },
  {
    id: "falling-glass-shards",
    name: "Falling Glass Shards",
    description: "Sharp refractive tetrahedrons raining down.",
    palette: ["#e0ffff", "#ccffff", "#ffffff"],
    background: { type: "gradient", color1: "#101010", color2: "#000000" },
    geometry: { type: "glassRain", count: 1500, sizeRange: [0.2, 0.6], material: "physical" },
    motion: { cameraDrift: true, cameraSpeed: 0.2, pattern: "linearFast", intensity: 0.6 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 0.9, glow: 0.6, grain: 0.05, chromaticAberration: 0.3 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 2000 }
  },
  {
    id: "8-bit-blizzard",
    name: "8-Bit Blizzard",
    description: "Massive voxels falling in a grid-aligned digital snowstorm.",
    palette: ["#ffffff", "#44aaff", "#0044aa"],
    background: { type: "solid", color1: "#001133" },
    geometry: { type: "voxelFall", count: 2000, sizeRange: [0.5, 0.5], material: "matte" },
    motion: { cameraDrift: true, cameraSpeed: 0.1, pattern: "linearFast", intensity: 0.5 },
    overlay: { glyphsEnabled: true, glyphStyle: "circuits", glyphOpacity: 0.2 },
    postProcessing: { bloom: 0.1, glow: 0.1, grain: 0.0, chromaticAberration: 0.0 },
    performance: { targetFPS: 60, quality: "medium", maxParticles: 2500 }
  },
  {
    id: "volcanic-ash-ember",
    name: "Volcanic Eruption",
    description: "Thick dark ash clouds mixed with bright glowing embers.",
    palette: ["#ff4400", "#ffaa00", "#111111", "#333333"],
    background: { type: "solid", color1: "#050000" },
    geometry: { type: "embers", count: 4000, sizeRange: [0.1, 0.5], material: "matte" },
    motion: { cameraDrift: true, cameraSpeed: 0.1, pattern: "explosion", intensity: 1.0 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 1.5, glow: 0.5, grain: 0.4, chromaticAberration: 0.1 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 5000 }
  },
  {
    id: "quantum-ribbons",
    name: "Quantum Ribbons",
    description: "Vibrating strings of energy interacting in a void.",
    palette: ["#ff0055", "#00ffaa", "#00ccff"],
    background: { type: "solid", color1: "#100010" },
    geometry: { type: "ribbonWave", count: 8, sizeRange: [1, 2], material: "neon" },
    motion: { cameraDrift: true, cameraSpeed: 0.3, pattern: "spiral", intensity: 1.0 },
    overlay: { glyphsEnabled: true, glyphStyle: "circuits", glyphOpacity: 0.2 },
    postProcessing: { bloom: 1.2, glow: 0.6, grain: 0.1, chromaticAberration: 0.3 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 20 }
  },
  {
    id: "emoji-universe-expansion",
    name: "Emoji Universe Expansion",
    description: "An infinite bang of pop-culture symbols.",
    palette: ["#ffff00", "#ff00ff", "#00ffff"],
    background: { type: "gradient", color1: "#220022", color2: "#000044" },
    geometry: { type: "emojiExplosion", count: 1200, sizeRange: [1.5, 4], material: "hologram", textChar: "✨🚀🌙⭐🌍🔥💎" },
    motion: { cameraDrift: true, cameraSpeed: 0.1, pattern: "explosion", intensity: 0.8 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 0.6, glow: 0.4, grain: 0.0, chromaticAberration: 0.1 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 1500 }
  },
  {
    id: "liquid-glow-flow",
    name: "Liquid Glow Flow",
    description: "Bioluminescent liquid moving in slow motion.",
    palette: ["#00ff44", "#0088cc", "#002244"],
    background: { type: "solid", color1: "#000510" },
    geometry: { type: "liquidField", count: 2000, sizeRange: [0.5, 1.0], material: "neon" },
    motion: { cameraDrift: true, cameraSpeed: 0.1, pattern: "noiseFlow", intensity: 0.3 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 1.5, glow: 1.0, grain: 0.1, chromaticAberration: 0.1 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 2000 }
  },
  {
    id: "code-geyser-special",
    name: "Code Geyser Overflow",
    description: "A high-pressure fountain of special characters ~!@#$%^&*.",
    palette: ["#00ff00", "#ccffcc", "#003300", "#ffffff"],
    background: { type: "solid", color1: "#050505" },
    geometry: { type: "characterGeyser", count: 1500, sizeRange: [0.5, 1.2], material: "neon", textChar: "~!@#$%^&*()?><+" },
    motion: { cameraDrift: true, cameraSpeed: 0.2, pattern: "explosion", intensity: 1.0 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 0.8, glow: 0.6, grain: 0.1, chromaticAberration: 0.2 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 2000 }
  },
  {
    id: "impact-highway",
    name: "Fracture Road Smash",
    description: "Particle clusters smashing into a wireframe road.",
    palette: ["#ff0055", "#00ffff", "#ffffff"],
    background: { type: "grid", color1: "#1a001a", color2: "#ff0055" },
    geometry: { type: "fractureRoad", count: 200, sizeRange: [0.2, 0.5], material: "metallic" },
    motion: { cameraDrift: false, cameraSpeed: 0.8, pattern: "linearFast", intensity: 1.0 },
    overlay: { glyphsEnabled: true, glyphStyle: "circuits", glyphOpacity: 0.1 },
    postProcessing: { bloom: 0.7, glow: 0.5, grain: 0.3, chromaticAberration: 0.4 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 1000 }
  },
  {
    id: "starship-launch",
    name: "Starship Ignition",
    description: "A rocket blasting off with massive exhaust plumes.",
    palette: ["#ffaa00", "#ff4400", "#555555", "#ffffff"],
    background: { type: "solid", color1: "#000000" },
    geometry: { type: "rocketLaunch", count: 3000, sizeRange: [0.1, 0.4], material: "metallic" },
    motion: { cameraDrift: true, cameraSpeed: 0.1, pattern: "noiseFlow", intensity: 1.0 },
    overlay: { glyphsEnabled: false, glyphStyle: "none", glyphOpacity: 0 },
    postProcessing: { bloom: 1.0, glow: 0.8, grain: 0.2, chromaticAberration: 0.1 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 4000 }
  },
  {
    id: "dna-evolution",
    name: "Genetic Evolution",
    description: "Rotating double helix strands of pure energy.",
    palette: ["#00f260", "#0575e6", "#ffffff"],
    background: { type: "nebula", color1: "#001133", color2: "#000000" },
    geometry: { type: "dnaSpiral", count: 2000, sizeRange: [0.1, 0.4], material: "glass" },
    motion: { cameraDrift: true, cameraSpeed: 0.1, pattern: "orbiting", intensity: 0.5 },
    overlay: { glyphsEnabled: true, glyphStyle: "zenRunes", glyphOpacity: 0.2 },
    postProcessing: { bloom: 0.8, glow: 0.4, grain: 0.1, chromaticAberration: 0.1 },
    performance: { targetFPS: 60, quality: "high", maxParticles: 2000 }
  },
  {
    id: "matrix-downpour",
    name: "System Failure Rain",
    description: "Heavy digital rain code falling in 3D space.",
    palette: ["#00ff00", "#008800", "#ccffcc"],
    background: { type: "solid", color1: "#000000" },
    geometry: { type: "matrixRain", count: 1500, sizeRange: [0.8, 1.2], material: "neon", textChar: "01" },
    motion: { cameraDrift: false, cameraSpeed: 0.0, pattern: "linearFast", intensity: 1.0 },
    overlay: { glyphsEnabled: true, glyphStyle: "matrixCode", glyphOpacity: 0.4 },
    postProcessing: { bloom: 0.9, glow: 0.7, grain: 0.15, chromaticAberration: 0.1 },
    performance: { targetFPS: 60, quality: "medium", maxParticles: 2000 }
  }
];